### ISSUE TITLE
Create User Accounts

### ISSUE THREAD

**Issue by brolyssjl** [AdminComission/quickinmobiliario#14]
Functionality for creating user accounts

**Comment by thomas1889** [comment]
Has to notice the following thing:

We have a corporative customers and also personal. Then it makes to have 2 different types in sign in forms

**Comment by brolyssjl** [comment]
Ya les generé un auth básico, es decir, que consiste en Login, Logout y Signin. Ya quedó actualizado en el layout y las vistas ya utilizan el nuevo layout ya que quedó renombrado a app en vez de main.
Actualicen sus respositorios locales y cualquier duda me comentan. 

Ya toca movernos porque ya veo que nos estamos atrasando :cry:.

**Comment by thomas1889** [comment]
@Stivenson02 Reunión despues de Almuerzo. 2pm
