### ISSUE TITLE
Suscription to Newsletter (form)

### ISSUE THREAD

**Issue by thomas1889** [AdminComission/quickinmobiliario#19]
Has to provide a form connected to mailchimp or similar tool to start to send them our news related to the time they had choosen. Ex: every week / 2 times a month or once a month.

**Comment by thomas1889** [comment]
Creen que necesitamos alguna  adición a nuestra base de datos? o simplemente usar alguna integración con sistemas existentes? Que sugerencia hay para realizar este tipo de tratamiento, teniendo en cuenta que van a ir tambien a un CRM.

**Comment by Stivenson02** [comment]
Un campo Newsletter en la tabla user, los campos se llenan por Si o No dependiendo, para diferenciarlos si esta o no suscrito a Newsletter
