### ISSUE TITLE
DB configuration

### ISSUE THREAD

**Issue by brolyssjl** [AdminComission/quickinmobiliario#2]
Configuración del Modelo de Datos de la aplicación.

**Comment by brolyssjl** [comment]
Traducción del modelo de datos y construcción con la ayuda de Laravel

**Comment by brolyssjl** [comment]
Inmuebles = Properties
ImagenesInmueble = PropertyImages

**Comment by brolyssjl** [comment]
TiposInmuebles = PropertyTypes
Acabados = Furnishes
Transancciones = Transactions
TiposNegocio = BussinessTypes
TipoUsos = UsageTypes
Proyectos = Projects
InmueblesAsociados = AssociatedProperties
Clientes = Clients
TiposUsuario = UserTypes
Usuarios = Users
Comisiones = Commisions
Citas = Appointments
Calificaciones = Qualifications
Peticiones = Queues
Planes = Prices

**Comment by thomas1889** [comment]
Table 

Proyectos  = Projects
___________________________
PK ->idProjects (INT)                                  idProyecto                                                               
name(VARCHAR 75)                                   nombre
Address (VARCHAR 75)                              direccion
Phone (VARCHAR 45)                                 telefono
Coordinates (POINT)                                  coordenadas
Description (TEXT)                                      descripcion
Built_Area (DECIMAL)                                 area_construida
Full_Area (DECIMAL)                                  area_lote
Zone (VARCHAR 45)                                  zona
City (VARCHAR 45)                                    ciudad
Neighborhood ( VARCHAR 45)                 barrio
FK -> Uses_Type (INT)                               TipoUsos_idTipoUso
FK -> Business_Type                                  TiposNegocio_idTipoNegocio

**Comment by Stivenson02** [comment]
inmueble = Property
imagenes Inmuebles= PropertyImage
Acabados = Furnisher
Tipo de Inmuebles= TypeProperty
Proyectos= Projects
Tipo de Negocio = BusinessType
Tipo de Usuario = UseType
Cliente = Clients
Inmueble Asociado = Associated property
Imagenes Proyectos = ProjectsImage
Usuarios = Users
Transacciones = Transactions
Comisiones= Commissions
Citas = Appointment
Calificaciones = Punctuation
Peticiones= Request
Planes= Plans

**Comment by brolyssjl** [comment]
## **Nombres oficiales de las tablas**

Inmuebles = Properties
ImagenesInmuebles= PropertyImages
Acabados = Furnishers
TiposInmuebles = PropertyTypes
Proyectos = Projects
TiposNegocio = BusinessTypes
TiposUsuario = UserTypes
Cliente = Clients
InmueblesAsociados = AssociatedProperties
ImagenesProyectos = ProjectImages
Usuarios = Users
Transacciones = Transactions
Comisiones = Commissions
Citas = Appointments
Calificaciones = Punctuations
Peticiones = Requests
Planes = PricePlans

**_Si hay nuevas sugerencias, editar este mismo comentario._**

**Comment by brolyssjl** [comment]
# **Nombres oficiales de las tablas intermedias del modelo de datos**

Usuarios_has_Inmuebles = users_has_properties
Usuarios_has_Proyectos = users_has_projects
Usuarios_has_planes = users_has_plans

**Comment by brolyssjl** [comment]
I just updated the repository with the migrations and models. Models already have relationships, so you can start to code. For now I'm going to create the seeds for the application; the seeds permit to generate random data for our tables. Please, check models, their relationships and migrations and any questions, we met.

**Comment by brolyssjl** [comment]
Si tienen dudas pregunten por favor, y si quieren nos reunimos para continuar por si algo no quedó claro. Espero comentarios

**Comment by thomas1889** [comment]
Gracias, Mañana Jueves entonces lo vemos.
